/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete;


 import AppPackage.AnimationClass;
/**
 *
 * @author Jonat
 */
public class programa extends javax.swing.JFrame {
    // contador es la Cantidad de passajeros
    public static int contador=0;
    // resultado es el total a pagar
    public static float resultado=0f; 
    // asumiendo que el precio del pasaje es estatico
    static final float pasajeEstandar=1.5f;
    /**
     * Creates new form programa
     */
    public programa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneltres = new javax.swing.JLabel();
        paneldos = new javax.swing.JLabel();
        botondebotones = new javax.swing.JLabel();
        botonadmin2 = new javax.swing.JLabel();
        botonadmin1 = new javax.swing.JLabel();
        botonadmin = new javax.swing.JLabel();
        botonpanel1 = new javax.swing.JLabel();
        click2 = new javax.swing.JButton();
        click1 = new javax.swing.JButton();
        resultadodelpago = new javax.swing.JLabel();
        resultadodelpago1 = new javax.swing.JLabel();
        cantidaddepasajeros1 = new javax.swing.JLabel();
        cancelarpaga = new javax.swing.JButton();
        confirmarPaga = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneltres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/Sin título-6.png"))); // NOI18N
        paneltres.setText("jLabel2");
        getContentPane().add(paneltres, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, 150, 350, 480));

        paneldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/Sin título-6.png"))); // NOI18N
        paneldos.setText("jLabel2");
        getContentPane().add(paneldos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, 150, 350, 480));

        botondebotones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botondebotones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/Sin título-7.png"))); // NOI18N
        botondebotones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botondebotonesMouseClicked(evt);
            }
        });
        getContentPane().add(botondebotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 140, 20));

        botonadmin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/imagen_2022-07-09_131154609-removebg-preview.png"))); // NOI18N
        botonadmin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonadmin2MouseClicked(evt);
            }
        });
        getContentPane().add(botonadmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 45, 80, 70));

        botonadmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/imagen_2022-07-09_131154609-removebg-preview.png"))); // NOI18N
        botonadmin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonadmin1MouseClicked(evt);
            }
        });
        getContentPane().add(botonadmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 45, 80, 70));

        botonadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/imagen_2022-07-09_131154609-removebg-preview.png"))); // NOI18N
        botonadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonadminMouseClicked(evt);
            }
        });
        getContentPane().add(botonadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 80, 70));

        botonpanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/Sin título-5.png"))); // NOI18N
        botonpanel1.setLabelFor(resultadodelpago1);
        botonpanel1.setText("jLabel2");
        getContentPane().add(botonpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 340, 480));

        click2.setBackground(new java.awt.Color(178, 203, 216));
        click2.setFont(new java.awt.Font("sansserif", 3, 48)); // NOI18N
        click2.setForeground(new java.awt.Color(255, 255, 255));
        click2.setText("-");
        click2.setToolTipText("");
        click2.setBorder(null);
        click2.setBorderPainted(false);
        click2.setContentAreaFilled(false);
        click2.setVerifyInputWhenFocusTarget(false);
        click2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                click2ActionPerformed(evt);
            }
        });
        getContentPane().add(click2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, 140, 140));

        click1.setBackground(new java.awt.Color(178, 203, 216));
        click1.setFont(new java.awt.Font("sansserif", 3, 48)); // NOI18N
        click1.setForeground(new java.awt.Color(255, 255, 255));
        click1.setText("+");
        click1.setToolTipText("");
        click1.setBorder(null);
        click1.setBorderPainted(false);
        click1.setContentAreaFilled(false);
        click1.setVerifyInputWhenFocusTarget(false);
        click1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                click1ActionPerformed(evt);
            }
        });
        getContentPane().add(click1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 140, 140));

        resultadodelpago.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        resultadodelpago.setForeground(new java.awt.Color(255, 255, 255));
        resultadodelpago.setText("0");
        getContentPane().add(resultadodelpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 190, 70));

        resultadodelpago1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        resultadodelpago1.setForeground(new java.awt.Color(255, 255, 255));
        resultadodelpago1.setText("S/");
        getContentPane().add(resultadodelpago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 40, 70));

        cantidaddepasajeros1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        cantidaddepasajeros1.setForeground(new java.awt.Color(255, 255, 255));
        cantidaddepasajeros1.setText("0");
        getContentPane().add(cantidaddepasajeros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 140, 70));

        cancelarpaga.setBackground(new java.awt.Color(216, 178, 178));
        cancelarpaga.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        cancelarpaga.setForeground(new java.awt.Color(255, 225, 225));
        cancelarpaga.setText("Cancelar");
        cancelarpaga.setBorder(null);
        cancelarpaga.setBorderPainted(false);
        cancelarpaga.setContentAreaFilled(false);
        cancelarpaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarpagaActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarpaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 514, 260, 60));

        confirmarPaga.setBackground(new java.awt.Color(178, 216, 193));
        confirmarPaga.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        confirmarPaga.setForeground(new java.awt.Color(255, 255, 255));
        confirmarPaga.setText("Continuar");
        confirmarPaga.setBorder(null);
        confirmarPaga.setBorderPainted(false);
        confirmarPaga.setContentAreaFilled(false);
        confirmarPaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarPagaActionPerformed(evt);
            }
        });
        getContentPane().add(confirmarPaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 514, 260, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/unknown.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshInterface(){
        // convierte las variables numero y resultado a string y lo refresca la interfaz
        String numero = String.valueOf(contador);
        cantidaddepasajeros1.setText(numero);
        String resultadoString = Float.toString(resultado);
       resultadodelpago.setText(resultadoString);
    }
    
    private void click2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_click2ActionPerformed
        // Evento al presionar el Boton de menos -
        // el condicional evita numeros negativos
        if (contador!=0){contador = contador - 1;}
        resultado = contador * pasajeEstandar;
        refreshInterface();
    }//GEN-LAST:event_click2ActionPerformed

    private void click1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_click1ActionPerformed
        // Evento al presionar el Boton de mas +
        contador = contador + 1;
        resultado = contador * pasajeEstandar;
        refreshInterface();
    }//GEN-LAST:event_click1ActionPerformed

    private void confirmarPagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarPagaActionPerformed
        this.setVisible(false);
        panel2 c= new panel2();
        c.setVisible(true);
        String numero = String.valueOf(contador);
        panel2.txtrecibi.setText(numero);
        String resultadoString = Float.toString(resultado);
        panel2.txtrecibi2.setText(resultadoString);
        //panel2.txtrecibi.setText(cantidaddepasajeros1.getText());
        //panel2.txtrecibi2.setText(resultadodelpago.getText());
    }//GEN-LAST:event_confirmarPagaActionPerformed

    private void cancelarpagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarpagaActionPerformed
        // reiniciar los valores
        contador = 0;
        resultado = 0f;
        refreshInterface();
    }//GEN-LAST:event_cancelarpagaActionPerformed

    private void botonadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonadminMouseClicked

        //panel mostrado
        AnimationClass  botonadminuno = new AnimationClass();
        botonadminuno.jLabelXRight(-340, 10, 10, 5, botonpanel1);
        
        //paneles ocultos
        AnimationClass  botonadminun = new AnimationClass();
        botonadminun.jLabelXLeft(10, -340, 10, 5, paneldos);
        
        AnimationClass  botonadminunn = new AnimationClass();
        botonadminunn.jLabelXLeft(10, -340, 10, 5, paneltres); 
    }//GEN-LAST:event_botonadminMouseClicked

    private void botondebotonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botondebotonesMouseClicked
        
        AnimationClass botondebotoness = new AnimationClass();
        botondebotoness.jLabelYDown(-80, 45, 10, 5, botonadmin);
        
        AnimationClass botondebotoness1 = new AnimationClass();
        botondebotoness1.jLabelYDown(-80, 45, 10, 5, botonadmin1);
        
        AnimationClass botondebotoness2 = new AnimationClass();
        botondebotoness2.jLabelYDown(-80, 45, 10, 5, botonadmin2);
        
        // ^^ bajar  | vv subir
        
        AnimationClass botondebotonesss = new AnimationClass();
        botondebotonesss.jLabelYUp(45, -80, 10, 5, botonadmin);
        
        AnimationClass botondebotonesss1 = new AnimationClass();
        botondebotonesss.jLabelYUp(45, -80, 10, 5, botonadmin1);
        
        AnimationClass botondebotonesss2 = new AnimationClass();
        botondebotonesss.jLabelYUp(45, -80, 10, 5, botonadmin2);
        
    }//GEN-LAST:event_botondebotonesMouseClicked

    private void botonadmin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonadmin1MouseClicked
        
        //paneles mostrado
        AnimationClass  botona = new AnimationClass();
        botona.jLabelXRight(-340, 10, 10, 5, paneldos);
        
        //paneles ocultos
        AnimationClass  botonadminun = new AnimationClass();
        botonadminun.jLabelXLeft(10, -340, 10, 5, botonpanel1);
        
        AnimationClass  botonadminunn = new AnimationClass();
        botonadminunn.jLabelXLeft(10, -340, 10, 5, paneltres); 
         
        
    }//GEN-LAST:event_botonadmin1MouseClicked

    private void botonadmin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonadmin2MouseClicked
       
        //paneles mostrado
        AnimationClass  botonadminunn = new AnimationClass();
        botonadminunn.jLabelXRight(-340, 10, 10, 5, paneltres); 
        
        
        //paneles ocultos
        AnimationClass  botonadminun = new AnimationClass();
        botonadminun.jLabelXLeft(10, -340, 10, 5, botonpanel1);
        
        AnimationClass  botonadminunnn = new AnimationClass();
        botonadminunnn.jLabelXLeft(10, -340, 10, 5, paneldos);
    }//GEN-LAST:event_botonadmin2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonadmin;
    private javax.swing.JLabel botonadmin1;
    private javax.swing.JLabel botonadmin2;
    private javax.swing.JLabel botondebotones;
    private javax.swing.JLabel botonpanel1;
    private javax.swing.JButton cancelarpaga;
    public static javax.swing.JLabel cantidaddepasajeros1;
    private javax.swing.JButton click1;
    private javax.swing.JButton click2;
    private javax.swing.JButton confirmarPaga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel paneldos;
    private javax.swing.JLabel paneltres;
    public static javax.swing.JLabel resultadodelpago;
    private javax.swing.JLabel resultadodelpago1;
    // End of variables declaration//GEN-END:variables
}
