/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete;

/**
 *
 * @author Jonat
 */
public class programa extends javax.swing.JFrame {

    int contador;
    /**
     * Creates new form programa
     */
    public programa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        click2 = new javax.swing.JButton();
        click1 = new javax.swing.JButton();
        resultadodelpago = new javax.swing.JLabel();
        resultadodelpago1 = new javax.swing.JLabel();
        cantidaddepasajeros1 = new javax.swing.JLabel();
        cancelarpaga = new javax.swing.JButton();
        confirmarPaga = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        click2.setBackground(new java.awt.Color(178, 203, 216));
        click2.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        click2.setText("-");
        click2.setToolTipText("");
        click2.setVerifyInputWhenFocusTarget(false);
        click2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                click2ActionPerformed(evt);
            }
        });
        getContentPane().add(click2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 100, 110));

        click1.setBackground(new java.awt.Color(178, 203, 216));
        click1.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        click1.setText("+");
        click1.setToolTipText("");
        click1.setVerifyInputWhenFocusTarget(false);
        click1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                click1ActionPerformed(evt);
            }
        });
        getContentPane().add(click1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 90, 110));

        resultadodelpago.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        resultadodelpago.setText("0");
        getContentPane().add(resultadodelpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 190, 70));

        resultadodelpago1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        resultadodelpago1.setText("S/");
        getContentPane().add(resultadodelpago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 190, 70));

        cantidaddepasajeros1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        cantidaddepasajeros1.setText("0");
        getContentPane().add(cantidaddepasajeros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 140, 70));

        cancelarpaga.setBackground(new java.awt.Color(216, 178, 178));
        cancelarpaga.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        cancelarpaga.setText("Cancelar");
        cancelarpaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarpagaActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarpaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, 120, -1));

        confirmarPaga.setBackground(new java.awt.Color(178, 216, 193));
        confirmarPaga.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        confirmarPaga.setText("Continuar");
        confirmarPaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarPagaActionPerformed(evt);
            }
        });
        getContentPane().add(confirmarPaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paquete/unknown.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void click2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_click2ActionPerformed
           contador = 0;
           
           String numero = String.valueOf(contador);
        cantidaddepasajeros1.setText(numero);
        
           String resultado = String.valueOf(contador);
        resultadodelpago.setText(numero);
        
        
           
    }//GEN-LAST:event_click2ActionPerformed

    private void click1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_click1ActionPerformed

         contador ++;
        String numero = String.valueOf(contador);
       cantidaddepasajeros1.setText(numero);
       
      double conta = 1.50;
        String resultado = String.valueOf(conta);
       resultadodelpago.setText(resultado);
      
       
    }//GEN-LAST:event_click1ActionPerformed

    private void confirmarPagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarPagaActionPerformed
            this.setVisible(false);
            panel2 c= new panel2();
            c.setVisible(true);
            
            
            panel2.txtrecibi.setText(cantidaddepasajeros1.getText());
            panel2.txtrecibi2.setText(resultadodelpago.getText());
    }//GEN-LAST:event_confirmarPagaActionPerformed

    private void cancelarpagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarpagaActionPerformed
        contador = 0;
           String numero = String.valueOf(contador);
         
        cantidaddepasajeros1.setText(numero);
     
        resultadodelpago.setText(numero);
    }//GEN-LAST:event_cancelarpagaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarpaga;
    public static javax.swing.JLabel cantidaddepasajeros1;
    private javax.swing.JButton click1;
    private javax.swing.JButton click2;
    private javax.swing.JButton confirmarPaga;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel resultadodelpago;
    private javax.swing.JLabel resultadodelpago1;
    // End of variables declaration//GEN-END:variables
}
